version: 2
jobs:
  build:
    machine: true
    working_directory: ~/docker-superset

    steps:

      - run:
         name: Build Docker image
         command: docker build -t abhioncbr/docker-superset:0.29.rc4 -f ./docker-files/DockerFile .

      - run:
          name: Push to DockerHub
          command: |
            docker login -u $DOCKERHUB_LOGIN -p $DOCKERHUB_PASSWORD
            docker push abhioncbr/docker-superset:0.29.rc4

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build